### ISSUE TITLE
Consider other browsers (the web is not Chrome only)

### ISSUE THREAD

**Issue by tobozo** [gpac/mp4box-sw#2]
or at least explain why there is no support for those
[edit]
FF has support for services workers ( https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API ) while MSIE/Opera/Safari have none.
So wha't wrong with Firefox ?

**Comment by cconcolato** [comment]
I certainly don't want the web to be Chrome-only. This is experimental development and it works where I can make it work. Feel free to participate. I would love to have this work in FF. Unfortunately, I have no idea why it's not working in FF. Debugging Service Workers in FF does not seem possible today as indicated on the [Mozilla Service Worker Status Page](https://wiki.mozilla.org/MDN/Get_involved/Events/HackOnMDN/Project:_Service_Workers).

**Comment by tobozo** [comment]
Thanks for the insight, could this be of some help for debugging : https://jakearchibald.github.io/isserviceworkerready/demos/postMessage/ ?

**Comment by cconcolato** [comment]
This is now working on FF, thanks to @wanderview.

**Comment by wanderview** [comment]
For the record, I think the underlying problem is we don't support <iterable> on the fetch Headers object yet.  So things like request.headers.forEach() do not work in Firefox at the moment.

We're working on fixing this in https://bugzilla.mozilla.org/show_bug.cgi?id=1108181
